'use server';
/**
 * @fileOverview Generates Next.js code based on a given task description.
 *
 * - generateCode - A function that generates code based on a task description.
 * - GenerateCodeInput - The input type for the generateCode function.
 * - GenerateCodeOutput - The return type for the generateCode function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import { GenerateCodeInputSchema, GenerateCodeOutputSchema, GenerateCodeInput, GenerateCodeOutput } from './schemas';

const prompt = ai.definePrompt({
  name: 'generateCodePrompt',
  input: {
    schema: GenerateCodeInputSchema,
  },
  output: {
    schema: GenerateCodeOutputSchema,
  },
  prompt: `You are an AI Developer agent specializing in generating Next.js code.

You will generate code based on the task description provided.

Task Description: {{{taskDescription}}}

Ensure the code is well-structured, efficient, and follows Next.js best practices.`,
});

export const generateCode = ai.defineFlow< // Directly export the result of ai.defineFlow
  typeof GenerateCodeInputSchema,
  typeof GenerateCodeOutputSchema
>(
  {
    name: 'generateCodeFlow',
    inputSchema: GenerateCodeInputSchema,
    outputSchema: GenerateCodeOutputSchema,
  },
  async input => {
    try {
      const {output} = await prompt(input);
      if (!output) {
        throw new Error('No output generated by the AI prompt.');
      }
      return {
        code: output.code,
        progress: 'Generated Next.js code based on the provided task description.',
      };
    } catch (error) {
      console.error('Error in generateCodeFlow:', error);
      // You might want to return a more specific error structure
      // that matches GenerateCodeOutputSchema or throw a custom error.
      // For now, re-throwing the original error or a generic one.
      throw new Error(`Failed to generate code: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
);
