'use server';
/**
 * @fileOverview A research AI agent that gathers information from the web.
 *
 * - researchTask - A function that handles the research process.
 * - ResearchTaskInput - The input type for the researchTask function.
 * - ResearchTaskOutput - The return type for the researchTask function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import { ResearchTaskInputSchema, ResearchTaskOutputSchema, ResearchTaskInput, ResearchTaskOutput } from './schemas';

const researchTaskPrompt = ai.definePrompt({
  name: 'researchTaskPrompt',
  input: {
    schema: ResearchTaskInputSchema,
  },
  output: {
    schema: ResearchTaskOutputSchema,
  },
  prompt: `You are a research agent tasked with gathering information from the web. Your goal is to find up-to-date and relevant information based on the search query provided. Provide a concise summary of the information you find.\n\nSearch Query: {{{query}}}`,
});

export const researchTask = ai.defineFlow< // Directly export the result of ai.defineFlow
  typeof ResearchTaskInputSchema,
  typeof ResearchTaskOutputSchema
>(
  {
    name: 'researchTaskFlow',
    inputSchema: ResearchTaskInputSchema,
    outputSchema: ResearchTaskOutputSchema,
  },
  async input => {
    try {
      const {output} = await researchTaskPrompt(input);
      if (!output) {
        throw new Error('No output generated by the AI prompt for research task.');
      }
      return output;
    } catch (error) {
      console.error('Error in researchTaskFlow:', error);
      throw new Error(`Failed to complete research task: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
);
