import { TestCodeInput, TestCodeOutput } from '../test-code';
// Do not import `ai` from `@/ai/ai-instance` here at the top level.

const mockPromptFn = jest.fn();
let capturedFlowLogic: ((input: TestCodeInput) => Promise<TestCodeOutput>) | undefined;

describe('testCode Flow', () => {
  beforeEach(() => {
    jest.resetModules();
    mockPromptFn.mockReset();
    capturedFlowLogic = undefined;
  });

  async function getMockedFlow() {
    let aiInstanceForAssertions: any;

    jest.doMock('@/ai/ai-instance', () => {
      const mockAi = {
        definePrompt: jest.fn().mockImplementation(() => mockPromptFn),
        defineFlow: jest.fn().mockImplementation((config: any, implementation: any) => {
          capturedFlowLogic = implementation;
          return jest.fn(async (input: TestCodeInput) => {
            if (!capturedFlowLogic) {
              throw new Error('Flow implementation logic not captured correctly.');
            }
            return capturedFlowLogic(input);
          });
        }),
      };
      aiInstanceForAssertions = mockAi;
      return { ai: mockAi };
    });

    const { testCode } = await import('../test-code');
    return { testCode, mockedAi: aiInstanceForAssertions };
  }

  it('should generate and report test results successfully with valid input', async () => {
    const { testCode } = await getMockedFlow();
    const input: TestCodeInput = {
      code: 'const MyComponent = () => <div>Hello</div>;',
      componentName: 'MyComponent',
    };
    const expectedOutput: TestCodeOutput = {
      tests: 'describe("MyComponent", () => { it("should render", () => {}); });',
      results: '1 test passed',
    };

    mockPromptFn.mockResolvedValue({ output: expectedOutput });

    expect(typeof testCode).toBe('function');
    const result = await testCode(input);

    expect(result).toEqual(expectedOutput);
    expect(mockPromptFn).toHaveBeenCalledWith(input);
  });

  it('should throw an error if the prompt returns no output', async () => {
    const { testCode } = await getMockedFlow();
    const input: TestCodeInput = {
      code: 'invalid code',
      componentName: 'ErrorComponent',
    };
    mockPromptFn.mockResolvedValue({ output: undefined });

    expect(typeof testCode).toBe('function');
    await expect(testCode(input)).rejects.toThrow('Failed to generate or run tests: No output generated by the AI prompt for test code generation.');
    expect(mockPromptFn).toHaveBeenCalledWith(input);
  });

  it('should throw an error if the prompt itself throws an error', async () => {
    const { testCode } = await getMockedFlow();
    const input: TestCodeInput = {
      code: 'const MyComponent = () => <div>Hello</div>;',
      componentName: 'MyComponent',
    };
    const promptError = new Error('Test generation engine failed');
    mockPromptFn.mockRejectedValue(promptError);

    expect(typeof testCode).toBe('function');
    await expect(testCode(input)).rejects.toThrow(`Failed to generate or run tests: ${promptError.message}`);
    expect(mockPromptFn).toHaveBeenCalledWith(input);
  });

  it('should ensure ai.definePrompt and ai.defineFlow were called on module load', async () => {
    const { mockedAi } = await getMockedFlow();
    expect(mockedAi.definePrompt).toHaveBeenCalled();
    expect(mockedAi.defineFlow).toHaveBeenCalled();
  });
});
